/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ListService } from "../list.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ListCreateInput } from "./ListCreateInput";
import { List } from "./List";
import { ListFindManyArgs } from "./ListFindManyArgs";
import { ListWhereUniqueInput } from "./ListWhereUniqueInput";
import { ListUpdateInput } from "./ListUpdateInput";
import { AccessPermissionFindManyArgs } from "../../accessPermission/base/AccessPermissionFindManyArgs";
import { AccessPermission } from "../../accessPermission/base/AccessPermission";
import { AccessPermissionWhereUniqueInput } from "../../accessPermission/base/AccessPermissionWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ListControllerBase {
  constructor(
    protected readonly service: ListService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: List })
  @nestAccessControl.UseRoles({
    resource: "List",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createList(@common.Body() data: ListCreateInput): Promise<List> {
    return await this.service.createList({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        expiresAt: true,
        id: true,
        name: true,
        privacy: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [List] })
  @ApiNestedQuery(ListFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "List",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async lists(@common.Req() request: Request): Promise<List[]> {
    const args = plainToClass(ListFindManyArgs, request.query);
    return this.service.lists({
      ...args,
      select: {
        createdAt: true,
        description: true,
        expiresAt: true,
        id: true,
        name: true,
        privacy: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: List })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "List",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async list(
    @common.Param() params: ListWhereUniqueInput
  ): Promise<List | null> {
    const result = await this.service.list({
      where: params,
      select: {
        createdAt: true,
        description: true,
        expiresAt: true,
        id: true,
        name: true,
        privacy: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: List })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "List",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateList(
    @common.Param() params: ListWhereUniqueInput,
    @common.Body() data: ListUpdateInput
  ): Promise<List | null> {
    try {
      return await this.service.updateList({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          expiresAt: true,
          id: true,
          name: true,
          privacy: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: List })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "List",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteList(
    @common.Param() params: ListWhereUniqueInput
  ): Promise<List | null> {
    try {
      return await this.service.deleteList({
        where: params,
        select: {
          createdAt: true,
          description: true,
          expiresAt: true,
          id: true,
          name: true,
          privacy: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/accessPermissions")
  @ApiNestedQuery(AccessPermissionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AccessPermission",
    action: "read",
    possession: "any",
  })
  async findAccessPermissions(
    @common.Req() request: Request,
    @common.Param() params: ListWhereUniqueInput
  ): Promise<AccessPermission[]> {
    const query = plainToClass(AccessPermissionFindManyArgs, request.query);
    const results = await this.service.findAccessPermissions(params.id, {
      ...query,
      select: {
        createdAt: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        list: {
          select: {
            id: true,
          },
        },

        permission: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/accessPermissions")
  @nestAccessControl.UseRoles({
    resource: "List",
    action: "update",
    possession: "any",
  })
  async connectAccessPermissions(
    @common.Param() params: ListWhereUniqueInput,
    @common.Body() body: AccessPermissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accessPermissions: {
        connect: body,
      },
    };
    await this.service.updateList({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/accessPermissions")
  @nestAccessControl.UseRoles({
    resource: "List",
    action: "update",
    possession: "any",
  })
  async updateAccessPermissions(
    @common.Param() params: ListWhereUniqueInput,
    @common.Body() body: AccessPermissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accessPermissions: {
        set: body,
      },
    };
    await this.service.updateList({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/accessPermissions")
  @nestAccessControl.UseRoles({
    resource: "List",
    action: "update",
    possession: "any",
  })
  async disconnectAccessPermissions(
    @common.Param() params: ListWhereUniqueInput,
    @common.Body() body: AccessPermissionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      accessPermissions: {
        disconnect: body,
      },
    };
    await this.service.updateList({
      where: params,
      data,
      select: { id: true },
    });
  }
}
