/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AccessPermissionService } from "../accessPermission.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AccessPermissionCreateInput } from "./AccessPermissionCreateInput";
import { AccessPermission } from "./AccessPermission";
import { AccessPermissionFindManyArgs } from "./AccessPermissionFindManyArgs";
import { AccessPermissionWhereUniqueInput } from "./AccessPermissionWhereUniqueInput";
import { AccessPermissionUpdateInput } from "./AccessPermissionUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AccessPermissionControllerBase {
  constructor(
    protected readonly service: AccessPermissionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AccessPermission })
  @nestAccessControl.UseRoles({
    resource: "AccessPermission",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAccessPermission(
    @common.Body() data: AccessPermissionCreateInput
  ): Promise<AccessPermission> {
    return await this.service.createAccessPermission({
      data: {
        ...data,

        group: data.group
          ? {
              connect: data.group,
            }
          : undefined,

        list: data.list
          ? {
              connect: data.list,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        list: {
          select: {
            id: true,
          },
        },

        permission: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AccessPermission] })
  @ApiNestedQuery(AccessPermissionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AccessPermission",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async accessPermissions(
    @common.Req() request: Request
  ): Promise<AccessPermission[]> {
    const args = plainToClass(AccessPermissionFindManyArgs, request.query);
    return this.service.accessPermissions({
      ...args,
      select: {
        createdAt: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        list: {
          select: {
            id: true,
          },
        },

        permission: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AccessPermission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AccessPermission",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async accessPermission(
    @common.Param() params: AccessPermissionWhereUniqueInput
  ): Promise<AccessPermission | null> {
    const result = await this.service.accessPermission({
      where: params,
      select: {
        createdAt: true,

        group: {
          select: {
            id: true,
          },
        },

        id: true,

        list: {
          select: {
            id: true,
          },
        },

        permission: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AccessPermission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AccessPermission",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAccessPermission(
    @common.Param() params: AccessPermissionWhereUniqueInput,
    @common.Body() data: AccessPermissionUpdateInput
  ): Promise<AccessPermission | null> {
    try {
      return await this.service.updateAccessPermission({
        where: params,
        data: {
          ...data,

          group: data.group
            ? {
                connect: data.group,
              }
            : undefined,

          list: data.list
            ? {
                connect: data.list,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          group: {
            select: {
              id: true,
            },
          },

          id: true,

          list: {
            select: {
              id: true,
            },
          },

          permission: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AccessPermission })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AccessPermission",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAccessPermission(
    @common.Param() params: AccessPermissionWhereUniqueInput
  ): Promise<AccessPermission | null> {
    try {
      return await this.service.deleteAccessPermission({
        where: params,
        select: {
          createdAt: true,

          group: {
            select: {
              id: true,
            },
          },

          id: true,

          list: {
            select: {
              id: true,
            },
          },

          permission: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
